[functions]
    directory = "functions/"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*"
  [headers.values]
    Access-Control-Allow-Origin = "*"


